"""initial_identity_tables

Revision ID: 36d3a7aeceab
Revises: 
Create Date: 2025-11-27 08:05:51.462106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d3a7aeceab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_permissions_id'), 'core_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_core_permissions_name'), 'core_permissions', ['name'], unique=True)
    op.create_table('core_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_roles_id'), 'core_roles', ['id'], unique=False)
    op.create_index(op.f('ix_core_roles_name'), 'core_roles', ['name'], unique=True)
    op.create_table('core_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_users_email'), 'core_users', ['email'], unique=True)
    op.create_index(op.f('ix_core_users_id'), 'core_users', ['id'], unique=False)
    op.create_table('core_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['core_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_user_roles')
    op.drop_index(op.f('ix_core_users_id'), table_name='core_users')
    op.drop_index(op.f('ix_core_users_email'), table_name='core_users')
    op.drop_table('core_users')
    op.drop_index(op.f('ix_core_roles_name'), table_name='core_roles')
    op.drop_index(op.f('ix_core_roles_id'), table_name='core_roles')
    op.drop_table('core_roles')
    op.drop_index(op.f('ix_core_permissions_name'), table_name='core_permissions')
    op.drop_index(op.f('ix_core_permissions_id'), table_name='core_permissions')
    op.drop_table('core_permissions')
    # ### end Alembic commands ###